### ISSUE TITLE
Validation for scouting form submission

### ISSUE THREAD

**Issue by YonatanNitzan** [Spikes-2212-Programming-Guild/mercury-web#22]
https://github.com/Spikes-2212-Programming-Guild/mercury-web/blob/05d70bb5590bb87c082eb94f9a0200e370104ee4/src/views/scouting-form.js#L47

Stop the user from submitting a form with empty fields.

**Comment by itamargreen** [comment]
@YonatanNitzan I forgot to tell you during the meeting: generally an issue's name is better when it gives a tiny description of the problem. In this case, validation of what?

**Comment by YonatanNitzan** [comment]
https://github.com/Spikes-2212-Programming-Guild/mercury-web/blob/bef838cf76b9770fc76e2e172b7bd0dd8748ce07/src/views/scouting-form.js#L60

What if no option is selected in the radio group? It doesn't stop the user from submitting - I've checked.
