### ISSUE TITLE
Mobile supported and user friendly UI

### ISSUE THREAD

**Issue by YonatanNitzan** [Spikes-2212-Programming-Guild/mercury-web#28]
Mobile support, additional buttons, styling, and so on...

**Comment by Jelomite** [comment]
You should leave styling as the last part. On the next weekend I'll come and help with UX/UI

**Comment by YonatanNitzan** [comment]
Next weekend?
We were planning to do it this weekend...
Do you think we should start without your help or just do mobile support, for example?

**Comment by Jelomite** [comment]
If that's the case, you shouldn't wait for me, do as planned. But on the weekend I'll come and help with improving the styling.

**Comment by YonatanNitzan** [comment]
Great. Thanks.

**Comment by itamargreen** [comment]
I'll try and help tomorrow towards the end of the meeting.

**Comment by YonatanNitzan** [comment]
Mobile supported (IOS not tested)

**Comment by YonatanNitzan** [comment]
Fully mobile supported.
